language: python
python:
  - "3.7.4"
  - "3.7.6"
  - "3.8.0"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov=. --cov-report=term-missing